file_path: ./datasets/bank-additional-full.csv
test_ratio: 0.2
model: xgb
model_params:
  max_depth: 4
  learning_rate: 0.1
  n_estimators: 50
  use_label_encoder: false
  n_jobs: 24

val_ratio: 0.2
coreset_val_ratio: 0.7
repeat_j: 1
val_method: kfold
k: 5

val_aug_iter_num: 20
add_ratio_per_iter: 0.1
diff_threshold_ratio: 0.02
aug_method: SMOTE
early_stop_threshold: 3
try_num_limits: 150
aug_sample_method: RS
add_num_decay_rate: 0.5
add_num_decay_method: triggered
add_num_decay_stage:


cal_distribution: false