file_path: ../datasets/car_evaluation.csv
test_ratio: 0.3
model: xgb
model_params:
  max_depth: 4
  learning_rate: 0.1
  n_estimators: 50
  use_label_encoder: false
  n_jobs: 24

val_ratio: 0.2
coreset_val_ratio: 0.7
val_method: aug_holdout
k: 1

val_aug_iter_num: 10
add_ratio_per_iter: 0.4
diff_threshold_ratio: 0.008
aug_method: SMOTE
aug_sample_method: RS
early_stop_threshold: 2
try_num_limits: 300
add_num_decay_rate: 0.5
add_num_decay_method:
add_num_decay_stage:


cal_distribution: false

